[package]
name = "libipld-core"
version = "0.7.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Base traits and definitions used by ipld codecs."
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
anyhow = "1.0.34"
cid = "0.6.0"
multibase = "0.9.1"
multihash = "0.13.1"
thiserror = "1.0.22"
