[package]
name = "libipld-core"
version = "0.4.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Base traits and definitions used by ipld codecs."
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
anyhow = "1.0.32"
multibase = "0.8.0"
thiserror = "1.0.20"
tiny-cid = "0.2.5"
tiny-multihash = "0.4.5"
